-- MySQL Script generated by MySQL Workbench
-- 06/21/17 10:19:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca` DEFAULT CHARACTER SET utf8 ;
USE `biblioteca` ;

-- -----------------------------------------------------
-- Table `biblioteca`.`tb_autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`tb_autor` (
  `id_autor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `origem` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_autor`),
  UNIQUE INDEX `id_autor_UNIQUE` (`id_autor` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`tb_usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `matricula` int NOT NULL,
  `nome` VARCHAR(30) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`tb_livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`tb_livro` (
  `id_livro` INT NOT NULL AUTO_INCREMENT,
  `isbn` VARCHAR(13) NOT NULL,
  `nome` VARCHAR(20) NOT NULL,
  `editora` VARCHAR(20) NOT NULL,
  `anopublicacao` VARCHAR(4) NOT NULL,
  `id_autor` INT NOT NULL,
  PRIMARY KEY (`id_livro`),
  INDEX `fk_tb_livro_tb_autor_idx` (`id_autor` ASC),
  UNIQUE INDEX `id_livro_UNIQUE` (`id_livro` ASC),
  CONSTRAINT `fk_tb_livro_tb_autor`
    FOREIGN KEY (`id_autor`)
    REFERENCES `biblioteca`.`tb_autor` (`id_autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`tb_retirada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`tb_retirada` (
  `id_retirada` INT NOT NULL AUTO_INCREMENT,
  `tb_usuario_id_usuario` INT NOT NULL,
  `tb_livro_id_livro` VARCHAR(13) NOT NULL,
  `dataEntrada` DATE NOT NULL,
  `dataSaida` DATE NOT NULL,
  PRIMARY KEY (`id_retirada`),
  UNIQUE INDEX `id_retirada_UNIQUE` (`id_retirada` ASC),
  INDEX `fk_tb_retirada_tb_livro_idx` (`tb_livro_id_livro` ASC),
  INDEX `fk_tb_retirada_tb_usuario_idx` (`tb_usuario_id_usuario` ASC),
  CONSTRAINT `fk_tb_retirada_tb_livro`
    FOREIGN KEY (`tb_livro_id_livro`)
    REFERENCES `biblioteca`.`tb_livro` (`id_livro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_retirada_tb_usuario`
    FOREIGN KEY (`tb_usuario_id_usuario`)
    REFERENCES `biblioteca`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
